-- Para ejecutal el script ejecutar el SQL Comand Line:
-- @C:\SQL\sosaramos_matiasantonio_2.sql

-- Conexion al Sitema;
CONNECT system/admin;

-- Si existe el usuario matias, lo elimino con todos sus objetos para probar una y otra vez;
DROP USER matias CASCADE;

-- Creacion de usuario:
CREATE USER matias IDENTIFIED BY admin DEFAULT TABLESPACE users TEMPORARY TABLESPACE temp QUOTA UNLIMITED ON users;

-- Asignacion de permisos al usuario:
GRANT CREATE SESSION, CREATE TABLE TO matias;

-- Desconectar Usuario SYSTEM
DISCONNECT system;

-- Conexion de usuario:
CONNECT matias/admin;

-- Creacion de la tabla Regiones
CREATE TABLE REGIONES (
	REGION_ID NUMBER NOT NULL,
	NOMBRE_REGION VARCHAR2(25),
	CONSTRAINT REGION_ID_PK PRIMARY KEY (REGION_ID)
);

-- Creacion de la tabla Paises
CREATE TABLE PAISES (
	PAIS_ID CHAR(2) NOT NULL,
	NOMBRE_PAIS VARCHAR2(40),
	REGION_ID NUMBER,
	CONSTRAINT PAIS_ID_PK PRIMARY KEY (PAIS_ID),
	CONSTRAINT REGION_ID_FK FOREIGN KEY (REGION_ID) REFERENCES REGIONES(REGION_ID)
);

-- Creacion de la tabla Localidades
CREATE TABLE LOCALIDADES (
	LOCALIDAD_ID NUMBER(4,0),
	DIRECCION VARCHAR2(40),
	CODIGO_POSTAL VARCHAR2(12),
	CIUDAD VARCHAR2(30) NOT NULL,
	ESTADO_PROVINCIA VARCHAR(25),
	PAIS_ID CHAR(2),
	CONSTRAINT LOCALIDAD_ID_PK PRIMARY KEY (LOCALIDAD_ID),
	CONSTRAINT LOCALIDAD_PAIS_FK FOREIGN KEY (PAIS_ID) REFERENCES PAISES(PAIS_ID)
);

-- Creacion de la tabla trabajos
CREATE TABLE TRABAJOS (
	TRABAJO_ID VARCHAR2(10) NOT NULL,
	TRABAJO_TITULO VARCHAR2(35) NOT NULL,
	SALARIO_MINIMO NUMBER(6,0),
	SALARIO_MAXIMO NUMBER(6,0),
	CONSTRAINT TRABAJO_ID_PK PRIMARY KEY (TRABAJO_ID)
);

-- Creacion de la tabla Departamento
CREATE TABLE DEPARTAMENTOS (
	DEPARTAMENTO_ID NUMBER(4,0) NOT NULL,
	DEPARTAMENTO_NOMBRE VARCHAR2(30) NOT NULL,
	GERENTE_ID NUMBER(6,0),
	LOCALIDAD_ID NUMBER(4,0),
	CONSTRAINT DEPARTAMENTO_ID_PK PRIMARY KEY (DEPARTAMENTO_ID)
	CONSTRAINT LOCALIDAD_ID_FK FOREIGN KEY (LOCALIDAD_ID) REFERENCES LOCALIDAD (LOCALIDAD_ID)
);

-- Creacion de la tabla Empleados
CREATE TABLE EMPLEADOS (
	EMPLEADO_ID NUMBER(6,0) NOT NULL,
	PRIMER_NOMBRE VARCHAR2(20),
	APELLIDO VARCHAR2(25) NOT NULL,
	EMAIL VARCHAR2(25) NOT NULL,
	CELULAR VARCHAR2(20),
	FECHA_CONTRATO DATE NOT NULL,
	TRABAJO_ID VARCHAR2(10) NOT NULL,
	SALARIO NUMBER(8,2),
	COMISION_PCT NUMBER(2,2),
	DEPARTAMENTO_ID NUMBER(4),
	GERENTE_ID NUMBER(6),
	CONSTRAINT EMPLEADO_SALARIO_MIN CHECK (SALARIO > 0),
	CONSTRAINT EMPLEADO_EMAIL_UNI UNIQUE(EMAIL),
	CONSTRAINT EMPLEADOS_EMPLEADO_ID_PK PRIMARY KEY (EMPLEADO_ID),
	CONSTRAINT EMPLEADO_DEPARTAMENTO_FK FOREIGN KEY (DEPARTAMENTO_ID) REFERENCES DEPARTAMENTOS (DEPARTAMENTO_ID),
	CONSTRAINT EMPLEADO_TRABAJOS_FK FOREIGN KEY (TRABAJO_ID) REFERENCES TRABAJOS (TRABAJO_ID),
	CONSTRAINT EMPLEADO_JEFE_FK FOREIGN KEY (GERENTE_ID) REFERENCES EMPLEADOS (EMPLEADO_ID)
);

-- Creacion de la tabla historial trabajo
CREATE TABLE HISTORIAL_TRABAJO (
	EMPLEADO_ID NUMBER(6) NOT NULL,
	FECHA_INICIO DATE NOT NULL,
	FECHA_FIN DATE NOT NULL,
	TRABAJO_ID VARCHAR2(10) NOT NULL,
	DEPARTAMENTO_ID NUMBER(4),
	CONSTRAINT CONTROL_FECHAS_INICIO_FIN CHECK (FECHA_INICIO < FECHA_FIN),
	CONSTRAINT HIST_TRABAJO_EMPLEADO_ID_PK PRIMARY KEY (EMPLEADO_ID, FECHA_INICIO),
	CONSTRAINT HIST_TRABAJO_FK FOREIGN KEY (TRABAJO_ID) REFERENCES TRABAJOS(TRABAJO_ID),
	CONSTRAINT HIST_EMPLEADO_FK FOREIGN KEY (EMPLEADO_ID) REFERENCES EMPLEADOS(EMPLEADOS_ID),
	CONSTRAINT HIST_DEPT_FK FOREIGN KEY (DEPARTAMENTO_ID) REFERENCES DEPARTAMENTOS(DEPARTAMENTO_ID)
);

-- ALTERS en Departamento
ALTER TABLE DEPARTAMENTOS ADD CONSTRAINT DPTO_GERENTE_ID FOREIGN KEY (GERENTE_ID) REFERENCES EMPLEADOS (EMPLEADO_ID);

-- INSERTS en la tabla regiones
INSERT INTO REGIONES(REGION_ID, NOMBRE_REGION)
VALUES (1, 'AMERICA DEL NORTE');

INSERT INTO REGIONES(REGION_ID, NOMBRE_REGION)
VALUES (2, 'AMERICA DEL SUR');

INSERT INTO REGIONES(REGION_ID, NOMBRE_REGION)
VALUES (3, 'AMERICA CENTRAL');

INSERT INTO REGIONES(REGION_ID, NOMBRE_REGION)
VALUES (4, 'ASIA ORIENTAL');

INSERT INTO REGIONES(REGION_ID, NOMBRE_REGION)
VALUES (4, 'ASIA DEL NORTE');

-- INSERTS EN LA TABLA PAISES
INSERT INTO PAISES(PAIS_ID, NOMBRE_PAIS, REGION_ID)
VALUES('1', 'PARAGUAY', 2);

INSERT INTO PAISES(PAIS_ID, NOMBRE_PAIS, REGION_ID)
VALUES('2', 'ARGENTINA', 2);

INSERT INTO PAISES(PAIS_ID, NOMBRE_PAIS, REGION_ID)
VALUES('3', 'BRAZIL', 2);

INSERT INTO PAISES(PAIS_ID, NOMBRE_PAIS, REGION_ID)
VALUES('4', 'BOLIVIA', 2);

INSERT INTO PAISES(PAIS_ID, NOMBRE_PAIS, REGION_ID)
VALUES('5', 'PERU', 2);

-- INSERTS en la tabla localidades
INSERT INTO LOCALIDADES(LOCALIDAD_ID, DIRECCION, CODIGO_POSTAL, CIUDAD, ESTADO_PROVINCIA, PAIS_ID)
VALUES(1, "RUTA 1", "1000", "CAPIATA", "CENTRAL", "1");

INSERT INTO LOCALIDADES(LOCALIDAD_ID, DIRECCION, CODIGO_POSTAL, CIUDAD, ESTADO_PROVINCIA, PAIS_ID)
VALUES(2, "RUTA 2", "1002", "CAPIATA", "CENTRAL", "1");

INSERT INTO LOCALIDADES(LOCALIDAD_ID, DIRECCION, CODIGO_POSTAL, CIUDAD, ESTADO_PROVINCIA, PAIS_ID)
VALUES(3, "RUTA 3", "1004", "CAPIATA", "CENTRAL", "1");

INSERT INTO LOCALIDADES(LOCALIDAD_ID, DIRECCION, CODIGO_POSTAL, CIUDAD, ESTADO_PROVINCIA, PAIS_ID)
VALUES(4, "RUTA 4", "1006", "CAPIATA", "CENTRAL", "1");

INSERT INTO LOCALIDADES(LOCALIDAD_ID, DIRECCION, CODIGO_POSTAL, CIUDAD, ESTADO_PROVINCIA, PAIS_ID)
VALUES(5, "RUTA 5", "1008", "CAPIATA", "CENTRAL", "1");

-- INSERT en la tabla TRABAJOS
INSERT INTO TRABAJOS(TRABAJO_ID, TRABAJO_TITULO, SALARIO_MINIMO, SALARIO_MAXIMO)
VALUES("001", "DEVELOPER BACKEND", 300, 600);

INSERT INTO TRABAJOS(TRABAJO_ID, TRABAJO_TITULO, SALARIO_MINIMO, SALARIO_MAXIMO)
VALUES("002", "DEVELOPER FRONTEND", 200, 400);

INSERT INTO TRABAJOS(TRABAJO_ID, TRABAJO_TITULO, SALARIO_MINIMO, SALARIO_MAXIMO)
VALUES("3", "DEVELOPER MOBILE", 400, 800);

INSERT INTO TRABAJOS(TRABAJO_ID, TRABAJO_TITULO, SALARIO_MINIMO, SALARIO_MAXIMO)
VALUES("4", "DEVOPS", 400, 800);

INSERT INTO TRABAJOS(TRABAJO_ID, TRABAJO_TITULO, SALARIO_MINIMO, SALARIO_MAXIMO)
VALUES("5", "DBA", 400, 800);

-- INSERT en la tabla DEPARTAMENTOS
INSERT INTO DEPARTAMENTOS(DEPARTAMENTO_ID, DEPARTAMENTO_NOMBRE, GERENTE_ID, LOCALIDAD_ID)
VALUES(1, "DESARROLLO", 1, 1);

INSERT INTO DEPARTAMENTOS(DEPARTAMENTO_ID, DEPARTAMENTO_NOMBRE, GERENTE_ID, LOCALIDAD_ID)
VALUES(2, "RECURSOS HUMANOS", 2, 1);

INSERT INTO DEPARTAMENTOS(DEPARTAMENTO_ID, DEPARTAMENTO_NOMBRE, GERENTE_ID, LOCALIDAD_ID)
VALUES(3, "TESTING", 3, 1);

INSERT INTO DEPARTAMENTOS(DEPARTAMENTO_ID, DEPARTAMENTO_NOMBRE, GERENTE_ID, LOCALIDAD_ID)
VALUES(4, "GERENCIA", 4, 1);

INSERT INTO DEPARTAMENTOS(DEPARTAMENTO_ID, DEPARTAMENTO_NOMBRE, GERENTE_ID, LOCALIDAD_ID)
VALUES(5, "AUDITORIA", 5, 1);

-- INSERT en la tabla Empleados
INSERT INTO EMPLEADOS(EMPLEADO_ID, PRIMER_NOMBRE, APELLIDO, EMAIL, CELULAR, FECHA_CONTRATO, TRABAJO_ID, SALARIO, COMISION_PCT, DEPARTAMENTO_ID, GERENTE_ID)
VALUES(1, "MATIAS", "SOSA", "sosa@gmail.com", "0982505151", '2020-01-01', 1, 300, 20, 1, 4);

INSERT INTO EMPLEADOS(EMPLEADO_ID, PRIMER_NOMBRE, APELLIDO, EMAIL, CELULAR, FECHA_CONTRATO, TRABAJO_ID, SALARIO, COMISION_PCT, DEPARTAMENTO_ID, GERENTE_ID)
VALUES(2, "MIGUEL", "LOPEZ", "lopez@gmail.com", "0982505154", '2020-01-02', 1, 300, 20, 1, 4);

INSERT INTO EMPLEADOS(EMPLEADO_ID, PRIMER_NOMBRE, APELLIDO, EMAIL, CELULAR, FECHA_CONTRATO, TRABAJO_ID, SALARIO, COMISION_PCT, DEPARTAMENTO_ID, GERENTE_ID)
VALUES(3, "MIGUEL", "GONZALEZ", "gonzalez@gmail.com", "0982505156", '2020-01-03', 1, 300, 20, 1, 4);

INSERT INTO EMPLEADOS(EMPLEADO_ID, PRIMER_NOMBRE, APELLIDO, EMAIL, CELULAR, FECHA_CONTRATO, TRABAJO_ID, SALARIO, COMISION_PCT, DEPARTAMENTO_ID, GERENTE_ID)
VALUES(4, "DENIS", "CABALLERO", "caballero@gmail.com", "0982505158", '2020-01-04', 1, 300, 20, 1, 4);

INSERT INTO EMPLEADOS(EMPLEADO_ID, PRIMER_NOMBRE, APELLIDO, EMAIL, CELULAR, FECHA_CONTRATO, TRABAJO_ID, SALARIO, COMISION_PCT, DEPARTAMENTO_ID, GERENTE_ID)
VALUES(5, "MATEO", "RAMOS", "ramos@gmail.com", "0982505160", '2020-01-05', 1, 300, 20, 1, 4);

-- INSERT de la tabla historial trabajo
INSERT INTO HISTORIAL_TRABAJO(EMPLEADO_ID, FECHA_INICIO, FECHA_FIN, TRABAJO_ID, DEPARTAMENTO_ID)
VALUES(1, '2020-01-01', '2020-12-12', 1)

INSERT INTO HISTORIAL_TRABAJO(EMPLEADO_ID, FECHA_INICIO, FECHA_FIN, TRABAJO_ID, DEPARTAMENTO_ID)
VALUES(2, '2020-01-02', '2020-12-12', 1)

INSERT INTO HISTORIAL_TRABAJO(EMPLEADO_ID, FECHA_INICIO, FECHA_FIN, TRABAJO_ID, DEPARTAMENTO_ID)
VALUES(3, '2020-01-03', '2020-12-12', 1)

INSERT INTO HISTORIAL_TRABAJO(EMPLEADO_ID, FECHA_INICIO, FECHA_FIN, TRABAJO_ID, DEPARTAMENTO_ID)
VALUES(4, '2020-01-04', '2020-12-12', 1)

INSERT INTO HISTORIAL_TRABAJO(EMPLEADO_ID, FECHA_INICIO, FECHA_FIN, TRABAJO_ID, DEPARTAMENTO_ID)
VALUES(5, '2020-01-05', '2020-12-12', 1)
